import type { GenerationTask } from './types'

const now = Date.now()

export const SEED_TASKS: GenerationTask[] = [
  {
    id: 'task-1',
    prompt: 'Неоновый киберпанк-город под дождём, вид сверху',
    type: 'image',
    model: 'Midjourney v6',
    status: 'running',
    progress: 64,
    createdAt: now - 120_000,
    startedAt: now - 90_000,
    credits: 80,
  },
  {
    id: 'task-2',
    prompt: 'Дрон-облёт горного озера на рассвете, 5 сек',
    type: 'video',
    model: 'Kling 3.0',
    status: 'running',
    progress: 28,
    createdAt: now - 180_000,
    startedAt: now - 150_000,
    credits: 150,
  },
  {
    id: 'task-3',
    prompt: 'Сценарий рекламного ролика для кофейни, 30 секунд',
    type: 'text',
    model: 'GPT-4o',
    status: 'queued',
    progress: 0,
    createdAt: now - 60_000,
    credits: 6,
    queuePosition: 3,
  },
  {
    id: 'task-4',
    prompt: 'Минималистичный логотип кофейни, бежевые тона',
    type: 'image',
    model: 'Flux',
    status: 'done',
    progress: 100,
    createdAt: now - 300_000,
    startedAt: now - 290_000,
    completedAt: now - 250_000,
    credits: 80,
  },
  {
    id: 'task-5',
    prompt: 'Озвучка приветствия мужским голосом',
    type: 'audio',
    model: 'ElevenLabs',
    status: 'failed',
    progress: 0,
    createdAt: now - 240_000,
    startedAt: now - 230_000,
    error: 'Недостаточно кредитов',
    credits: 15,
  },
  {
    id: 'task-6',
    prompt: 'Постер в стиле ретро-футуризм 80-х',
    type: 'image',
    model: 'Seedream',
    status: 'canceled',
    progress: 0,
    createdAt: now - 200_000,
    credits: 40,
  },
  {
    id: 'task-7',
    prompt: 'Таймлапс строительства небоскрёба, 10 сек',
    type: 'video',
    model: 'Kling 3.0',
    status: 'queued',
    progress: 0,
    createdAt: now - 30_000,
    credits: 200,
    queuePosition: 1,
  },
  {
    id: 'task-8',
    prompt: 'Описание продукта для маркетплейса, стиль casual',
    type: 'text',
    model: 'GPT-4o',
    status: 'queued',
    progress: 0,
    createdAt: now - 20_000,
    credits: 4,
    queuePosition: 2,
  },
  {
    id: 'task-9',
    prompt: 'Портрет девушки в стиле импрессионизм',
    type: 'image',
    model: 'Flux',
    status: 'done',
    progress: 100,
    createdAt: now - 500_000,
    startedAt: now - 490_000,
    completedAt: now - 420_000,
    credits: 60,
  },
  {
    id: 'task-10',
    prompt: 'Фоновая музыка для медитации, 60 секунд',
    type: 'audio',
    model: 'ElevenLabs',
    status: 'queued',
    progress: 0,
    createdAt: now - 10_000,
    credits: 25,
    queuePosition: 4,
  },
]
